name: Comment on lint failure

on:
  workflow_run:
    workflows:
      - Lint
    types:
      - completed

concurrency:
  group: "${{github.workflow}}-${{github.event.workflow_run.event}}-${{github.event.workflow_run.head_repository.full_name}}:${{github.event.workflow_run.head_branch}}"
  cancel-in-progress: true

jobs:
  comment_on_lint_failure:
    name: Comment on lint failure
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
        github.event.workflow_run.conclusion == 'failure'
    steps:
      - uses: ipdxco/workflow-run-context@492ea3967eb2ca7ed76b7888b42fa7649addd975 # v1.1.1
        name: Get workflow run context
        id: context
        with:
          artifacts-url: ${{ github.event.workflow_run.artifacts_url }}
          artifact-names: event
      - uses: actions/github-script@v6
        name: Comment on failure
        env:
          NUMBER: ${{ fromJSON(steps.context.outputs.artifacts)['event'].files['event.json'].number }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: process.env.NUMBER,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thanks for submitting this PR!\n\nUnfortunately, it has some linter errors, so we can't merge it yet. Can you please fix them?\n\nRunning pnpm lint:fix in the root of the repository may fix them automatically."
            })
